# Form implementation generated from reading ui file 'designer/confirmationdialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfirmationDialog(object):
    def setupUi(self, ConfirmationDialog):
        ConfirmationDialog.setObjectName("ConfirmationDialog")
        ConfirmationDialog.resize(405, 215)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfirmationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconLabel = QtWidgets.QLabel(parent=ConfirmationDialog)
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_2.addWidget(self.iconLabel)
        self.titleLabel = QtWidgets.QLabel(parent=ConfirmationDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(parent=ConfirmationDialog)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonGroupBox = QtWidgets.QGroupBox(parent=ConfirmationDialog)
        self.buttonGroupBox.setTitle("")
        self.buttonGroupBox.setObjectName("buttonGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(parent=self.buttonGroupBox)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.confirmButton = QtWidgets.QPushButton(parent=self.buttonGroupBox)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.verticalLayout.addWidget(self.buttonGroupBox)

        self.retranslateUi(ConfirmationDialog)
        QtCore.QMetaObject.connectSlotsByName(ConfirmationDialog)

    def retranslateUi(self, ConfirmationDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfirmationDialog.setWindowTitle(_translate("ConfirmationDialog", "Dialogue de confirmation"))
        self.iconLabel.setText(_translate("ConfirmationDialog", "pixmap"))
        self.titleLabel.setText(_translate("ConfirmationDialog", "Le titre"))
        self.cancelButton.setText(_translate("ConfirmationDialog", "Annuler"))
        self.confirmButton.setText(_translate("ConfirmationDialog", "Confirmer"))
