# Form implementation generated from reading ui file 'designer/fontdialogwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FontDialog(object):
    def setupUi(self, FontDialog):
        FontDialog.setObjectName("FontDialog")
        FontDialog.resize(556, 511)
        FontDialog.setMinimumSize(QtCore.QSize(0, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FontDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=FontDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=FontDialog)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.textEdit = QtWidgets.QTextEdit(parent=FontDialog)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.saveButton = QtWidgets.QPushButton(parent=FontDialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_2.addWidget(self.saveButton)
        spacerItem = QtWidgets.QSpacerItem(20, 242, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(FontDialog)
        QtCore.QMetaObject.connectSlotsByName(FontDialog)

    def retranslateUi(self, FontDialog):
        _translate = QtCore.QCoreApplication.translate
        FontDialog.setWindowTitle(_translate("FontDialog", "Réglages"))
        self.label.setText(_translate("FontDialog", "Taille de la police"))
        self.textEdit.setHtml(_translate("FontDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Une fois la police enregistrée, le dialogue se fermera et vous devrez redémarrer l\'application pour voir les changements.</p></body></html>"))
        self.saveButton.setText(_translate("FontDialog", "Enregistrer"))
