# Form implementation generated from reading ui file 'designer/helpwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_helpWidget(object):
    def setupUi(self, helpWidget):
        helpWidget.setObjectName("helpWidget")
        helpWidget.resize(1068, 582)
        self.horizontalLayout = QtWidgets.QHBoxLayout(helpWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=helpWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout.addWidget(self.groupBox)
        self.textEdit = QtWidgets.QTextEdit(parent=helpWidget)
        self.textEdit.setStyleSheet("padding-left:20px;background-color:transparent")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        self.retranslateUi(helpWidget)
        QtCore.QMetaObject.connectSlotsByName(helpWidget)

    def retranslateUi(self, helpWidget):
        _translate = QtCore.QCoreApplication.translate
        helpWidget.setWindowTitle(_translate("helpWidget", "Aide générale de l’application"))
        self.groupBox.setTitle(_translate("helpWidget", "GroupBox"))
